wavezGen/WebWavez/Controllers/CancionController.cs
using Microsoft.AspNetCore.Mvc;
using System.Drawing;
using WavezGen.ApplicationCore.CEN.Wavez;
using WavezGen.ApplicationCore.EN.Wavez;
using WavezGen.Infraestructure.Repository.Wavez;
using WebWavez.Assemblers;
using WebWavez.Models;

namespace WebWavez.Controllers
{
    public class CancionController : BasicController
    {

        private readonly Microsoft.AspNetCore.Hosting.IWebHostEnvironment _webHost;

        public CancionController(Microsoft.AspNetCore.Hosting.IWebHostEnvironment webHost)
        {
            _webHost = webHost;
        }

        // GET: CancionController
        public ActionResult Index()
        {
            SessionInitialize();
            CancionRepository cancionRepository = new CancionRepository(session);
            CancionCEN cancionCEN = new CancionCEN(cancionRepository);
            IList<CancionEN> listaENs = cancionCEN.DameTodasLasCanciones(0, -1);

            IEnumerable<CancionViewModel> listaCanciones = new CancionAssembler().ConvertirListENToListViewModel(listaENs);
            SessionClose();

            return View(listaCanciones);
        }

        // GET: CancionController/Details/5
        public ActionResult Details(int id)
        {
            SessionInitialize();
            Console.WriteLine("Estamos aqui {CancionController} -> " + id);
            CancionRepository cancionRepository = new CancionRepository(session);
            CancionCEN cancionCEN = new CancionCEN(cancionRepository);
            CancionEN cancionEN = cancionCEN.DameCancionPorOID(id);
            CancionViewModel cancion = new CancionAssembler().CovertirENToViewModel(cancionEN);
          
            ComentarioRepository comentarioRepository = new ComentarioRepository(session);
            ComentarioCEN comentarioCEN = new ComentarioCEN(comentarioRepository);
            IList<ComentarioEN> listaComentarios = comentarioCEN.DameTodosLosComentarios(0, -1);
            listaComentarios = listaComentarios.Where(c => c.Cancion != null && c.Cancion.Id == id).ToList();
            ViewBag.Comentarios = new ComentarioAssembler().ConvertirListENToListViewModel(listaComentarios);
     
            return View(cancion);
        }

        // GET: CancionController/Create
        public ActionResult Create()
        {
            var generosEnumValues = Enum.GetValues(typeof(WavezGen.ApplicationCore.Enumerated.Wavez.GenerosEnum))
                                        .Cast<WavezGen.ApplicationCore.Enumerated.Wavez.GenerosEnum>()
                                        .ToDictionary(g => (int)g, g => g.ToString());

            ViewBag.GenerosEnumDictionary = generosEnumValues;
            return View();
        }

        // POST: CancionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync(CancionViewModel cvm)
        {

            string CancionFileName = "", CancionPath = "";
            string FotoFileName = "", FotoPath = "";
            if (cvm.FicheroFotoPortada != null && cvm.FicheroCancion != null && cvm.FicheroCancion.Length > 0 && cvm.FicheroFotoPortada.Length > 0)
            {
                string timestamp = DateTime.Now.ToString("yyyyMMddHHmmssfff");
                CancionFileName = timestamp + Path.GetExtension(cvm.FicheroCancion.FileName);
                FotoFileName = timestamp + Path.GetExtension(cvm.FicheroFotoPortada.FileName);

                string fotoDirectory = _webHost.WebRootPath + "/Imagenes";
                string songDirectory = _webHost.WebRootPath + "/Canciones";

                string cancionPath = Path.Combine((songDirectory), CancionFileName);
                string fotoPath = Path.Combine((fotoDirectory), FotoFileName);

                if (!Directory.Exists(fotoDirectory))
                {
                    Directory.CreateDirectory(fotoDirectory);
                }

                if (!Directory.Exists(songDirectory))
                {
                    Directory.CreateDirectory(songDirectory);
                }

                using (var fileStream = new FileStream(cancionPath, FileMode.Create))
                {
                    await cvm.FicheroCancion.CopyToAsync(fileStream);
                }

                using (var fileStream = new FileStream(fotoPath, FileMode.Create))
                {
                    await cvm.FicheroFotoPortada.CopyToAsync(fileStream);
                }
            }
            try
            {
                UsuarioViewModel usuario = HttpContext.Session.Get<UsuarioViewModel>("usuario");

                CancionFileName = "/Canciones/" + CancionFileName;
                FotoFileName = "/Imagenes/" + FotoFileName;
                Console.WriteLine("Estamos aqui {Subiendo Cancion} -> " + CancionFileName + " " + FotoFileName);
                CancionRepository cancionRepository = new CancionRepository();
                CancionCEN cancionCEN = new CancionCEN(cancionRepository);
                int cancion_publicada = cancionCEN.Nuevo(cvm.Titulo, cvm.Genero, DateTime.Now, FotoFileName, usuario.Usuario, 1, CancionFileName);
                CancionEN cancionEN_publicada = cancionCEN.DameCancionPorOID(cancion_publicada);

                Console.WriteLine($"Cancion Publicada: {cancionEN_publicada.Titulo}");


                SessionInitialize();
                UsuarioRepository usuarioRepository = new UsuarioRepository(session);
                UsuarioCEN usuarioCEN = new UsuarioCEN(usuarioRepository);

                UsuarioEN publicador = usuarioCEN.DameUsuarioPorOID(usuario.Usuario);

                Console.WriteLine($"Publicador: {publicador.Nombre}");
                List<UsuarioEN> seguidores = usuarioCEN.DameTodosLosUsuarios(0, -1)
                    .Where(u => u.UsuarioSeguidos.Contains(publicador))
                    .ToList();
                SessionClose();

                Console.WriteLine($"FotoFileName: {FotoFileName}, Mensaje: {usuario.Nombre} ha subido una nueva cancion!, Fecha: {DateTime.Now}, TipoContenido: cancion, UsuarioPublicador: {publicador.Usuario}, UsuariosReceptores: {string.Join(", ", seguidores.Select(s => s.Usuario))}, CancionCompartida: {cancionEN_publicada}, PlaylistCompartida: new PlaylistEN()");

                NotificacionRepository notificacionRepository = new NotificacionRepository();
                NotificacionCEN notificacionCEN = new NotificacionCEN(notificacionRepository);

                ComunidadRepository comunidadRepository = new ComunidadRepository();
                ComunidadCEN comunidadCEN = new ComunidadCEN(comunidadRepository);
                ComunidadEN comunidad = comunidadCEN.DameComunidadPorOID(cvm.Genero);

                notificacionCEN.Nuevo(FotoFileName, 
                    usuario.Nombre + " ha subido una nueva cancion!", 
                    DateTime.Now, "cancion", 
                    publicador,
                    seguidores,
                    cancionEN_publicada, 
                    null);

                int notificacion_comunidad = notificacionCEN.NuevoConComunidad(FotoFileName,
                    $"Hay una nueva cancion para la comunidad {cvm.Genero.ToString()}!",
                    DateTime.Now, "cancion",
                    comunidad,
                    seguidores,
                    cancionEN_publicada,
                    null);

                Console.WriteLine($"Notificacion Comunidad: {notificacionCEN.DameNotificacionPorOID(notificacion_comunidad).Mensaje}");

                return RedirectToAction("Perfil", "Usuario", new { id = "me" });
                ;
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return View();
            }
        }

        // GET: CancionController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }
        [HttpPost]
        public IActionResult AumentarReproducciones(int id)
        {
            CancionRepository cancionRepository = new CancionRepository();
            CancionCEN cancionCEN = new CancionCEN(cancionRepository);
            cancionCEN.ReproducirCancion(id);

            // You can return some result if needed
            return Json(new { success = true });
        }

        // POST: CancionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CancionController/Delete/5
        public ActionResult Delete(int id)
        {
            CancionRepository cancionRepository = new CancionRepository();
            CancionCEN cancionCEN = new CancionCEN(cancionRepository);
            cancionCEN.Eliminar(id);
            return RedirectToAction("Perfil", "Usuario", new { id = "me" });
        }

        // POST: CancionController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

wavezGen/WebWavez/Controllers/PlaylistController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Transactions;
using System.Xml.Serialization;
using WavezGen.ApplicationCore.CEN.Wavez;
using WavezGen.ApplicationCore.EN.Wavez;
using WavezGen.Infraestructure.Repository.Wavez;
using WebWavez.Assemblers;
using WebWavez.Models;

namespace WebWavez.Controllers
{
    public class PlaylistController : BasicController
    {

        private readonly Microsoft.AspNetCore.Hosting.IWebHostEnvironment _webHost;

        public PlaylistController(Microsoft.AspNetCore.Hosting.IWebHostEnvironment webHost)
        {
            _webHost = webHost;
        }

        // GET: PlaylistController
        public ActionResult Index()
        {
            SessionInitialize();
            PlaylistRepository playlistRepository = new PlaylistRepository(session);
            PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);
            IList<PlaylistEN> listaENs = playlistCEN.DameTodasLasPlaylist(0, -1);

            IEnumerable<PlaylistViewModel> listaPlaylists = new PlaylistAssembler().ConvertirListENToListViewModel(listaENs);
            SessionClose();

            IList<PlaylistEN> misPlaylistsENs = dameMisPlaylists();
            IEnumerable<PlaylistViewModel> MisPlaylists = new PlaylistAssembler().ConvertirListENToListViewModel(misPlaylistsENs);

            // Pass the playlists to the view
            ViewBag.MisPlaylists = MisPlaylists;

            return View(listaPlaylists);
        }

        [HttpPost]
        public void AgregarCancionAPlaylist(int cancionOID, int playlistOID)
        {
            Console.WriteLine("Cancion: " + cancionOID.ToString());
            Console.WriteLine("Playlist " + playlistOID.ToString());

            var playlistRepository = new PlaylistRepository();
            var playlistCEN = new PlaylistCEN(playlistRepository);
            playlistCEN.AddCancion(playlistOID, new List<int> { cancionOID });
        
        }


        public IList<PlaylistEN> dameMisPlaylists()
        {

            SessionInitialize();
            PlaylistRepository playlistRepository = new PlaylistRepository(session);
            PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);
            IList<PlaylistEN> playlistENs = playlistCEN.DameTodasLasPlaylist(0, -1);
            IList<PlaylistEN> misPlaylists = new List<PlaylistEN>();
            UsuarioViewModel usuario = HttpContext.Session.Get<UsuarioViewModel>("usuario");

            foreach (PlaylistEN playlistEN in playlistENs)
            {
                if (playlistEN.UsuarioCreador.Usuario == usuario.Usuario)
                {
                    misPlaylists.Add(playlistEN);
                }
            }

            return misPlaylists;
        }
        
public string dameMisPlaylistJSON() // Lol JSON a mano
        {
            IList<PlaylistEN> misPlaylists = dameMisPlaylists();
            string texto = "{ ";
            texto += "\"playlists\":[";
            for (int i = 0; i < misPlaylists.Count; i++)
            {
                PlaylistEN playlist = misPlaylists[i];
                texto += "{ ";
                texto += "\"Id\":\"";
                texto += playlist.Id;
                texto += "\"";
                texto += ",";

                texto += "\"Titulo\":\"";
                texto += playlist.Titulo;
                texto += "\"";
                texto += "}";

                if (i < misPlaylists.Count - 1)
                {
                    texto += ",";
                }
            }
            texto += "]}";

            return texto;
        }

        // GET: PlaylistController/Details/5
        public ActionResult Details(int id)
        {
            SessionInitialize();
            PlaylistRepository playlistRepository = new PlaylistRepository(session);
            PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);
            PlaylistEN playlistEN = playlistCEN.DamePlaylistPorOID(id);

            if (playlistEN == null)
            {
                SessionClose();
                return NotFound();
            }

            PlaylistViewModel playlistViewModel = new PlaylistAssembler().ConvertirENToViewModel(playlistEN);

            // Fetch the songs in the playlist
            IList<CancionEN> cancionesEN = playlistEN.Cancion;
            IEnumerable<CancionViewModel> cancionesViewModel = new CancionAssembler().ConvertirListENToListViewModel(cancionesEN);
            ViewBag.Canciones = cancionesViewModel;

            SessionClose();

            // Pass the playlist and songs to the view
            return View(playlistViewModel);
        }

        // GET: PlaylistController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PlaylistController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync(PlaylistViewModel pvm)
        {

            string FotoFileName = "", FotoPath = "";
            if (pvm.FicheroFotoPortada != null && pvm.FicheroFotoPortada.Length > 0)
            {
                string timestamp = DateTime.Now.ToString("yyyyMMddHHmmssfff");
                FotoFileName = timestamp + Path.GetExtension(pvm.FicheroFotoPortada.FileName);

                string fotoDirectory = _webHost.WebRootPath + "/Imagenes";
                
                string fotoPath = Path.Combine((fotoDirectory), FotoFileName);

                if (!Directory.Exists(fotoDirectory))
                {
                    Directory.CreateDirectory(fotoDirectory);
                }


                using (var fileStream = new FileStream(fotoPath, FileMode.Create))
                {
                    await pvm.FicheroFotoPortada.CopyToAsync(fileStream);
                }
            }
            try
            {
                UsuarioViewModel usuario = HttpContext.Session.Get<UsuarioViewModel>("usuario");

                FotoFileName = "/Imagenes/" + FotoFileName;
                PlaylistRepository playlistRepository = new PlaylistRepository();
                PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);
                playlistCEN.Nuevo(pvm.Titulo, FotoFileName, usuario.Usuario);
                return RedirectToAction("Perfil", "Usuario", new { id = "me" });
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaylistController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PlaylistController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaylistController/Delete/5
        public ActionResult Delete(int id)
        {
            PlaylistRepository playlistRepository = new PlaylistRepository();
            PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);
            playlistCEN.Eliminar(id);
            return RedirectToAction("Perfil", "Usuario", new { id = "me" });
        }

        // POST: PlaylistController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                PlaylistRepository playlistRepository = new PlaylistRepository();
                PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);
                playlistCEN.Eliminar(id);
                return RedirectToAction("Perfil", "Usuario", new { id = "me" });
            }
            catch
            {
                return View();
            }
        }
    }
}

wavezGen/WebWavez/Views/Playlist/Details.cshtml
@model WebWavez.Models.PlaylistViewModel
@using Newtonsoft.Json
@{
    ViewData["Title"] = "View";
    IEnumerable<WebWavez.Models.CancionViewModel> Songs = ViewBag.Canciones;

    string cancionesJson = JsonConvert.SerializeObject(Songs);
}

<div class="card" id="card-detalle-cancion">
    <a asp-controller="Playlist" asp-action="Details" asp-route-id="@Model.Id" data-id="@Model.Id">
        <img class="card-img-top" style="text-align: center;" src="@Html.DisplayFor(model => model.FotoPortada)" style="height: 180px; width: 180px; border-radius: 6px;" alt="Card image cap" />
    </a>
    <div class="card-body">
        <h3 class="card-title" style="text-align: center;"><strong>@Html.DisplayFor(model => model.Titulo)</strong></h3>
    </div>
</div>
<div class="comentarios-cancion">
    <div class="comentarios">
        <div class="button-row" style="display: flex; flex-direction: row;">
            <button class="btn button" onclick="playlistPlay(event)"><i class="bi bi-play-fill"></i></button>
            <button class="btn button" onclick="playlistShufflePlay(event)"><i class="bi bi-shuffle"></i></button>
        </div>
    </div>
        @foreach (var song in Songs)
        {
            <div class="notificacion" style="display: flex; flex-direction: row; justify-content: start; align-items: center;">
                <a asp-controller="Cancion" asp-action="Details" asp-route-id="@song.Id">
                    <img src="@song.FotoPortada" style="height: 120px; width: 120px; border-radius: 6px;" />
                </a>
                <div class="info-notificacion">
                    <p style="font-size: 1.7rem;"><strong>@song.Titulo</strong></p>
                    <a asp-controller="Usuario" asp-action="Perfil" asp-route-id="@song.Autor">
                    <p>@song.AutorDisplay</p>
                    </a>
                </div>
            </div>
        }
    </div>
</div>


@section Scripts {
    <script>


        const canciones = @Html.Raw(cancionesJson);

        document.addEventListener("mousemove", (e) => {
            const circle = document.getElementById("mouse-circle");
            circle.style.transform = `translate(${e.pageX - 50}px, ${e.pageY - 50}px)`;
        });

        let songQueue = [];
        let isPlaying = false;

        // Obtener elementos clave
        const audioPlayer = document.getElementById('audioPlayer');
        const albumArt = document.getElementById('albumArt');
        const trackTitle = document.getElementById('trackTitle');
        const trackArtist = document.getElementById('trackArtist');
        const playPauseButton = document.getElementById('playPauseButton');
        const progress = document.getElementById('progress');
        const currentTimeEl = document.getElementById('currentTime');
        const durationEl = document.getElementById('duration');

        // Actualizar información del tiempo
        function formatTime(seconds) {
            const minutes = Math.floor(seconds / 60);
            const secs = Math.floor(seconds % 60).toString().padStart(2, '0');
            return `${minutes}:${secs}`;
        }

        function addToQueue(song) {
            songQueue.push(song);
            sessionStorage.setItem('songQueue', JSON.stringify(songQueue));
            console.log('Canción agregada a la cola:', song.title);
        }

        function playlistPlay(event) {
            event.preventDefault();
            songQueue = [];
            for (const song of canciones) {
                addToQueue({
                    id: song.Id,
                    url: song.Url,
                    albumArt: song.FotoPortada,
                    title: song.Titulo,
                });
            }
            sessionStorage.setItem('songQueue', JSON.stringify(songQueue));
            playNextInQueue();
        }

        function playlistShufflePlay(event) {
            event.preventDefault();
            songQueue = [];
            const shuffledSongs = canciones.sort(() => Math.random() - 0.5);
            for (const song of shuffledSongs) {
                addToQueue({
                    id: song.Id,
                    url: song.Url,
                    albumArt: song.FotoPortada,
                    title: song.Titulo,
                });
            }
            sessionStorage.setItem('songQueue', JSON.stringify(songQueue));
            playNextInQueue();
        }

        document.addEventListener('DOMContentLoaded', () => {
            // Asegurarnos de que las canciones estén disponibles
            if (!Array.isArray(canciones)) {
                console.error("No se encontraron canciones.");
                return;
            }
            console.log("Canciones disponibles:", canciones);
        });

        document.querySelectorAll('.play-button').forEach(a => {
            a.addEventListener('click', (e) => {
                e.preventDefault();
                console.log("Play Button Clicked!")
                const songId = a.getAttribute('data-id');
                const song = canciones.find(c => c.Id == songId);
                if (song) {
                    playSong({
                        id: song.Id,
                        url: song.Url,
                        albumArt: song.FotoPortada,
                        title: song.Titulo,
                        artist: song.Autor,
                    });
                } else {
                    console.error(`No se encontró la canción con ID ${songId}`);
                }
            });
        });


        function updateProgress() {
            const currentTime = audioPlayer.currentTime;
            const duration = audioPlayer.duration;

            progress.value = (currentTime / duration) * 100 || 0;
            currentTimeEl.textContent = formatTime(currentTime);
            durationEl.textContent = formatTime(duration);

            const value = progress.value;
            const max = progress.max;
            const percentage = (value / max) * 100;
            progress.style.setProperty('--progress', `${percentage}%`);
        }

        audioPlayer.addEventListener('timeupdate', updateProgress);
        audioPlayer.addEventListener('loadedmetadata', () => {

            const value = progress.value;
            const max = progress.max;
            const percentage = (value / max) * 100;
            progress.style.setProperty('--progress', `${percentage}%`);
            durationEl.textContent = formatTime(audioPlayer.duration);
        });
        // Cambiar el progreso manualmente
        progress.addEventListener('input', () => {
            const seekTime = (progress.value / 100) * audioPlayer.duration;
            audioPlayer.currentTime = seekTime;
        });

        // Pausar/Reanudar reproducción
        playPauseButton.addEventListener('click', () => {
            if (isPlaying) {
                audioPlayer.pause();
                playPauseButton.innerHTML = `<i class="bi bi-play-fill"></i>`;
                sessionStorage.setItem('isPlaying', 'false');
            } else {
                audioPlayer.play();
                playPauseButton.innerHTML = `<i class="bi bi-pause-fill"></i>`;
                sessionStorage.setItem('isPlaying', 'true');
            }
            isPlaying = !isPlaying;
        });

        // Reproducir la siguiente canción de la cola
        function playNextInQueue() {
            if (songQueue.length > 0) {
                const nextSong = songQueue.shift();
                sessionStorage.setItem('songQueue', JSON.stringify(songQueue)); // Actualizar cola en SessionStorage
                playSong(nextSong);
            } else {
                console.log('La cola está vacía.');
                isPlaying = false;
            }
        }
        // Recuperar cola y canción actual al cargar la página
        window.addEventListener('load', () => {
            const storedQueue = sessionStorage.getItem('songQueue');
            if (storedQueue) {
                songQueue = JSON.parse(storedQueue);
                console.log('Cola recuperada:', songQueue);
            }

            const currentSong = sessionStorage.getItem('currentSong');
            if (currentSong) {
                playSong(JSON.parse(currentSong));
            }

            // Restaurar tiempo de la canción
            const storedTime = sessionStorage.getItem('currentTime');
            if (storedTime) {
                audioPlayer.currentTime = parseFloat(storedTime);
            }

            // Restaurar estado de reproducción
            const storedIsPlaying = sessionStorage.getItem('isPlaying');
            if (storedIsPlaying === 'true') {
                audioPlayer.play();
                playPauseButton.innerHTML = `<i class="bi bi-pause-fill"></i>`;
                isPlaying = true;
            } else {
                audioPlayer.pause();
                playPauseButton.innerHTML = `<i class="bi bi-play-fill"></i>`;
                isPlaying = false;
            }
        });

        // Guardar tiempo de la canción al salir de la página
        window.addEventListener('beforeunload', () => {
            const currentTime = audioPlayer.currentTime;
            sessionStorage.setItem('currentTime', currentTime);
        });

        // Evento cuando una canción termina
        audioPlayer.addEventListener('ended', () => {
            console.log('Canción terminada.');
            playNextInQueue();
        });

        // Función para reproducir una canción
        async function playSong(song) {
            console.log("Reproduciendo " + JSON.stringify(song))
            if (!song || !song.url) return;
            audioPlayer.src = song.url;
            audioPlayer.load();
            audioPlayer.play();
            playPauseButton.innerHTML = `<i class="bi bi-pause-fill"></i>`;
            isPlaying = true;


            const value = progress.value;
            const max = progress.max;
            const percentage = (value / max) * 100;
            progress.style.setProperty('--progress', `${percentage}%`);


            // Actualizar información de la canción
            albumArt.src = song.albumArt || 'https://via.placeholder.com/100';
            trackTitle.textContent = song.title || 'Título desconocido';
            trackArtist.textContent = song.artist || 'Artista desconocido';

            sessionStorage.setItem('currentSong', JSON.stringify(song));
            console.log(`Reproduciendo canción: ${song.title}`);

            // Llamar a la API para aumentar reproducciones
            if (song.id) {
                try {
                    const response = await fetch('/Cancion/AumentarReproducciones', {
                        method: 'POST',
                        body: new URLSearchParams({ 'id': song.id })
                    });

                    const data = await response.json();
                    if (data.success) {
                        console.log("Reproducción aumentada exitosamente.");
                    } else {
                        console.log("Error al aumentar las reproducciones.");
                    }
                } catch (error) {
                    console.error("Error en la llamada a la API:", error);
                }
            }
        }
    </script>
}